c_compiler:
    - gcc  # [linux]
    - clang  # [osx]
    - m2w64-toolchain  # [win]

cxx_compiler:
    - gxx  # [linux]
    - clangxx  # [osx]
    - m2w64-toolchain  # [win]

fortran_compiler:
    - gfortran  # [linux]
    - gfortran  # [osx]
    - m2w64-toolchain  # [win]

# CMAKE_GENERATOR:  # [win]
#   - NMake Makefiles  # [win]
