c_compiler:
    - gcc        # [linux]
    - clang      # [osx]
    - m2w64_c    # [win]

cxx_compiler:
    - gxx        # [linux]
    - clangxx    # [osx]
    - m2w64_cxx  # [win]

fortran_compiler:
    - gfortran       # [linux]
    - gfortran       # [osx]
    - m2w64_fortran  # [win]

# CMAKE_GENERATOR:  # [win]
#   - NMake Makefiles  # [win]
