{% set name = "openfast" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

# source:
#   url: https://github.com/openfast/openfast/archive/v{{ version }}.tar.gz
#   sha256: 2b368e8c8211ebed03e87fb3e89ef733b7e4be4848834da4034f8419d618446c
#   # Download the tar-ball and do `openssl sha256 file.tar.gz` to update

source:
  git_url: https://github.com/rafmudaf/openfast.git
  git_rev: feature/simulink_support
  # git_depth: 1 # (Defaults to -1/not shallow)
  # path: /Users/rmudafor/Development/openfast/

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - make
    - cmake
  host:
    - libblas
    - liblapack

test:
  commands:
    - openfast -h

about:
  home: https://github.com/openfast/openfast
  license: Apache-2.0
  license_file: LICENSE
  summary: OpenFAST whole turbine simulation tool
  description: NREL-supported OpenFAST whole-turbine simulation code
  doc_url: http://openfast.readthedocs.io
  dev_url: https://github.com/openfast/openfast

extra:
  recipe-maintainers:
    - rafmudaf
    - openfast
